version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: db_trabajos_web
    restart: always
    networks:
      - app-network  # <--- CONECTADO
    environment:
      # Forma de Mapa (sin guiones)
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      APP_TIMEZONE: ${APP_TIMEZONE:-America/Guayaquil}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data    
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  scraper:
    build: ./04_TrabajosWeb_Scraper
    container_name: trabajos_scraper
    # Cambiamos tail -f por el inicio real de la app
    command: tail -f /dev/null
    working_dir: /app/src  # <--- Esto hace que 'src' sea la raíz
    tty: true
    stdin_open: true
    depends_on:
      - db
      - logs_service
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - APP_TIMEZONE=${APP_TIMEZONE:-America/Guayaquil}
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    
  logs_service:
    build: ./04_TrabajosWeb_Logs
    container_name: trabajos_logs
    networks:
      - app-network  # <--- CONECTADO
    volumes:
      - ./logs_storage:/app/storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:8000"
    environment:
    - APP_TIMEZONE=${APP_TIMEZONE:-America/Guayaquil} # <--- Aquí
      
networks:
  app-network:
    driver: bridge

volumes:
  db_data: